### ISSUE TITLE
StreamedRequest Fails on Large File Upload in Chrome When Tab Not in Focus

### ISSUE THREAD

**Issue by thiagocarvalhodev** [Zekfad/fetch_client#11]
Hello, first of all, thanks for the library and its maintenance. :) 

### Issue
We are experiencing an issue when uploading using the `StreamedRequest`. We are sending the file as the body of the request. Sometimes, for large files, for example, 500MiB, it causes the following error:

```
TypeError: Failed to fetch
POST https://example.com/upload net::ERR_FAILED
```

### Steps to reproduce
Here are the steps to reproduce it - Using Chrome
- Open a new instance
- Try uploading a file of 600MB. You can use the `openRead` API from the `File` object.
- As soon as the file starts uploading, switch to another app.
- Let the page lose focus for at least 3 or 4 minutes and the upload fails.
- If we come back after 3 or 4 minutes and it hasn't failed, let's switch away from the page for another 1 or 2 minutes.
- Then, let's return to our page.
- Upload fails.

### Related Issues/PRs:
Possibly related to: https://github.com/w3c/ServiceWorker/issues/1246

**Comment by Zekfad** [comment]
Have you set BaseRequest.persistentConnection to false?
This may be the work of the browser, to kill inactive tabs e.g. new chromium "memory saver".
As a side note, I may suggest you to try to use WebSockets if you're explicitly targeting browser and control the server.
Alternatively background worker may be the key, but that would probably require either extension or "web app".

**Comment by thiagocarvalhodev** [comment]
Thanks for answering! Do you have any guidance on how I could use the background worker + fetch? My app is primarily a Flutter Web app.

**Comment by Zekfad** [comment]
You would have to create dart script and manually compile it to JS, pass that script to worker.
Some docs from `web` package (upcoming js interop in replacement of dart:html, but they should be pretty much the same): https://api.flutter.dev/flutter/package-web_web/Worker-class.html

Also some old samples available: https://stackoverflow.com/questions/70880505/is-there-currently-a-way-to-compute-a-dart-function-with-webworkers 

If you need to use some common infrastructure of the app at the web you have 2 ways:
- Split up to some independent modules and import required parts in both the app and worker script.
- Try to make a wrapper JS script that would alternate app entrypoint if it is run in web worker. (E.g. wapper sets some global variable, you check for it in `main` function and alternate to run worker instead of running app).

In any case you would need to some way of passing data to worker, you probably would want to send JS File to worker, here's some info https://stackoverflow.com/questions/33306015/pass-submited-file-to-web-worker-by-refference-with-as-little-overhead-as-possib

As a side note, this seems to be an interesting task, I'll probably try to make a module to simplify this, but no promises yet :P

**Comment by Zekfad** [comment]
Also there is seems to be a good solution in this package: https://pub.dev/packages/isolate_manager

**Comment by Zekfad** [comment]
I'll close this for now, as this is most likely a browser feature we can't do anything about.

(It's also reasonable to kill background tabs that just wasting bandwidth, browser is not aware what is good or useless job, like ad streaming on background tab).

For anyone stumble upon this issue here are 2 recommendations:

- Suggest user not to unfocus tab (or tear it to new window and leave open on foreground)
- Use extension to provide background tasks even when tab is closed

**Comment by thiagocarvalhodev** [comment]
Thanks for the support and sorry for the late response. :(

We finally fixed the issue by mixing: 
- backpressure control https://github.com/ardriveapp/fetch_api/blob/ef5e490d063644d0e875a5402bcd9236e37bd2b1/lib/src/readable_stream_source/readable_stream_source.compatibility_layer.dart

- and... removing the `flutter_service_worker.js` by using the `pwa-strategy=none`. https://github.com/ardriveapp/ardrive-web/pull/1500.

Actually, we can fix this issue by removing the following code on the `flutter_service_worker.js`.

![image](https://github.com/Zekfad/fetch_client/assets/32248947/53e15117-bcd8-40be-b1e8-91847e490e37).

----

We are researching more about what's the real reason for the `flutter_service_worker.js` killing our request, and as soon as I get a solution, I'd be happy to share it. Again, thanks!

**Comment by Zekfad** [comment]
Thank you for your investigations!
I'm kind of lost why backpressure may help here, even without it data must be buffered on browser side. Especially if request was in progress.
Later on when we update `fetch_api` to new interop I hope to add that feature to general interface.
