### ISSUE TITLE
error got : "Client is closed"

### ISSUE THREAD

**Issue by bhaumik1111** [Zekfad/fetch_client#8]
-

**Comment by Zekfad** [comment]
You don't need to close client after request, you should close client only after you won't need it anymore.
That isn't issue with `fetch_client` or `http` that is desired behavior.
Closing client prevents it's future use (similar to use-after-free issues in cpp), what you probably meant is to close request.
Also from your snippet it's not recommend to decode utf-8 and concatenate strings, but rather concatenate buffer and then decode utf-8, because stream could be split in middle of surrogate pair.
You probably dont need streaming in first place if you just decide utf and then join results, because you could use related method and get full body decoded according to http spec.

**Comment by bhaumik1111** [comment]
i am not able to delete that question on github
did you know how to delete it?
